language: go

go:
- 1.11.x

before_install:
  # SDL bindings
  - sudo apt-get update
  - sudo apt-get install libegl1-mesa-dev
  - sudo apt-get install libgles2-mesa-dev
  - sudo apt-get install libsdl2{,-image,-mixer,-ttf,-gfx}-dev

  # Grab dep
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
