
[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/veandco/go-sdl2"
  version = "0.3.0"

[[constraint]]
  name = "github.com/faiface/beep"
  version = "1.0.1"
